- name: ufw firewall config file # update the sshd config file
  template: src=firewall/ufw_docker.j2
      dest=/etc/ufw/after.rules
      backup=yes
      owner=0 group=0 mode=0644      
  register: update 



- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Allow SSH connections
  community.general.ufw:
    rule: allow
    port: ssh

# - name: Allow incoming loopback connections
#   community.general.ufw:
#     rule: allow
#     interface_in: lo

# - name: Allow outgoing loopback connections
#   community.general.ufw:
#     rule: allow
#     interface_out: lo

- name: Restart UFW Service
  ansible.builtin.service:
      name: ufw
      state: restarted
      enabled: yes
  when: update.changed
