  - name: create ansible deploy user
    user:
      name: ansible
      create_home: yes
      groups: root

  - name: add ssh key for ansible
    authorized_key:
      user: ansible
      key: "{{ lookup('file', '~/.ssh/cloud.pub') }}"

  - name: add sudoers file for ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

