---
- name: Base Config for Remote Cloud hosts with root 
  hosts: cloud
  remote_user: root
  tasks:

  - name: Update and upgrade apt packages # Apt update && apt upgrade
    apt:
      update_cache: yes    
      upgrade: yes
      
  - name: Ensure Python3 is Installed and updated # Install/Update Python3
    apt:
      name: python3
      state: latest

  - name: delete authorized_keys file  # Deleate authorized_keys file
    ignore_errors: yes
    file:
      state: absent
      path: ~/.ssh/authorized_keys
 
  - name: create new authorized_keys file # generate new authorized_keys file
    ignore_errors: yes
    file:
      path: "~/.ssh/authorized_keys"
      state: touch
      
  - name: Insert SSH Key for Root Admin # SSH key only used for manual Root Admin login
    blockinfile:
      block: "{{ lookup('file', '~/.ssh/id_ed25519_sk.pub') }}"  
      path: ~/.ssh/authorized_keys

  - name: sshd configuration file update  # update the sshd config file
    template: src=sshd_config.j2
      dest=/etc/ssh/sshd_config
      backup=yes
      owner=0 group=0 mode=0644
      validate='/usr/sbin/sshd -T -f %s'  
  

  - name: Add ansible user and add it to sudo # Add Ansible user and move to sudo group
    ansible.builtin.user:
      name: ansible
      comment: Ansible Deploy User
      group: sudo
      create_home: yes
          
  - name: Set authorized key for ansible user  # Used for later Ansible Configuration
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
 
  - name: Add user ansible to sudo  # Add ansible user to sudoers
    lineinfile:
      path: /etc/sudoers.d/ansible
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'

  - name: Add dev user and add it to sudo # Add dev user and move to sudo group
    ansible.builtin.user:
      name: dev
      comment: development user
      group: sudo
      create_home: yes

  - name: Set authorized key for ansible user  # Used for later manual Configuration
    authorized_key:
      user: dev
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ed25519_sk.pub') }}"

  - name: Add user dev to sudo  # Add dev user to sudoers
    lineinfile:
      path: /etc/sudoers.d/dev
      line: 'dev ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'

  - name: Set includedir in sudoers # Ensure includedir is set in sudoers file
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

  - name: sshd configuration file update # update the sshd config file
    template: src=ssh/sshd_config.j2
      dest=/etc/ssh/sshd_config
      backup=yes
      owner=0 group=0 mode=0644
      validate='/usr/sbin/sshd -T -f %s'      

  - name: Restart SSH Service
    ansible.builtin.service:
      name: ssh
      state: restarted