- name: sshd configuration file update # update the sshd config file
  template: src=ssh/sshd_config.j2
      dest=/etc/ssh/sshd_config
      backup=yes
      owner=0 group=0 mode=0644
      validate='/usr/sbin/sshd -T -f %s'      
  register: update 


- name: Restart SSH Service
  ansible.builtin.service:
      name: ssh
      state: restarted
  when: update.changed